# 登入

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /v1/auth/login:
    post:
      summary: 登入
      deprecated: false
      description: ''
      tags:
        - 登入相关
      parameters:
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                udid:
                  type: string
                  title: 设备ID
                origin_transaction_id:
                  type: string
                  title: 订单ID
              required:
                - udid
                - origin_transaction_id
              x-apifox-orders:
                - udid
                - origin_transaction_id
            example:
              udid: cc71db73-9a78-4a9a-85c5-085075f287a3
              transaction_id: '2000000990568933'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        title: token
                      refresh_token:
                        type: string
                        title: 刷新token
                      access_expires_at:
                        type: integer
                        title: token过期时间
                        x-apifox-mock: '{{$date.timestamp}}'
                      refresh_expires_at:
                        type: integer
                        title: 刷新token过期时间
                        x-apifox-mock: '{{$date.timestamp}}'
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            title: ID
                          name:
                            type: string
                            title: 用户名
                          status:
                            type: integer
                            title: 状态
                          uuid:
                            type: string
                            title: 用户唯一ID
                          vip:
                            type: integer
                            title: vip 等级
                            enum:
                              - 0
                              - 1
                              - 2
                              - 3
                              - 4
                            x-apifox-enum:
                              - value: 0
                                name: 无会员
                                description: ''
                              - value: 1
                                name: 周会员
                                description: ''
                              - value: 2
                                name: 月会员
                                description: ''
                              - value: 3
                                name: 季会员
                                description: ''
                              - value: 4
                                name: 年会员
                                description: ''
                          vip_expired_time:
                            type: integer
                            title: vip 过期时间
                            x-apifox-mock: '{{$date.millisecondsTimestamp}}'
                        required:
                          - id
                          - name
                          - status
                          - uuid
                          - vip
                          - vip_expired_time
                        title: 用户信息
                        x-apifox-orders:
                          - id
                          - name
                          - status
                          - uuid
                          - vip
                          - vip_expired_time
                    required:
                      - token
                      - refresh_token
                      - access_expires_at
                      - refresh_expires_at
                      - user
                    x-apifox-orders:
                      - token
                      - refresh_token
                      - access_expires_at
                      - refresh_expires_at
                      - user
                  code:
                    type: integer
                    x-apifox-mock: '200000'
                required:
                  - message
                  - data
                  - code
                x-apifox-orders:
                  - message
                  - data
                  - code
              example:
                message: 操作成功！
                data:
                  token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwic3ViIjoiY2M3MWRiNzMtOWE3OC00YTlhLTg1YzUtMDg1MDc1ZjI4N2EzIiwiZXhwIjoxNzU1NDg2Mjk2LCJuYmYiOjE3NTU0ODI2OTYsImlhdCI6MTc1NTQ4MjY5NiwianRpIjoiODRmNGU5OWEtZTYxNS00MmUyLTljYmItMDlkZjZlMjBiNmU0In0.Z6Eg9bEG-_jHV3ee_qOCwo1RhqXxSbWw_R3ELTExCNc
                  refresh_token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsInN1YiI6ImNjNzFkYjczLTlhNzgtNGE5YS04NWM1LTA4NTA3NWYyODdhMyIsImV4cCI6MTc1NjA4NzQ5NiwibmJmIjoxNzU1NDgyNjk2LCJpYXQiOjE3NTU0ODI2OTYsImp0aSI6Ijg0ZjRlOTlhLWU2MTUtNDJlMi05Y2JiLTA5ZGY2ZTIwYjZlNCJ9.FF-X03saUG0juElvK4lXfQ0owBa0N2CMYla5FCQPxzc
                  access_expires_at: 1755486296
                  refresh_expires_at: 1756087496
                  user:
                    id: 14
                    name: C3hkN7by
                    status: 0
                    uuid: cc71db73-9a78-4a9a-85c5-085075f287a3
                    vip: 0
                    vip_expired_time: 0
                code: 200000
          headers: {}
          x-apifox-name: 成功
      security: []
      x-apifox-folder: 登入相关
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-347371356-run
components:
  schemas: {}
  securitySchemes: {}
servers:
  - url: ''
    description: 云端 Mock
security: []

```

# 刷新 token

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /v1/auth/refresh-token:
    post:
      summary: 刷新 token
      deprecated: false
      description: ''
      tags:
        - 登入相关
      parameters:
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  title: 刷新token
                  description: 请注意使用的是刷新 token
              required:
                - refresh_token
              x-apifox-orders:
                - refresh_token
            example:
              refresh_token: >-
                eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsInN1YiI6ImNjNzFkYjczLTlhNzgtNGE5YS04NWM1LTA4NTA3NWYyODdhMyIsImV4cCI6MTc1NjA5MzA4MSwibmJmIjoxNzU1NDg4MjgxLCJpYXQiOjE3NTU0ODgyODEsImp0aSI6ImFkNGNlOGUxLTEzZTQtNDhjMC1iMjEwLTU0MmMyNTdkNThiZSJ9.ekDnVFO8vYk3oP0mcl_l_WOnHYdRlZSTzs8hH5DWLsM
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        title: token
                      refresh_token:
                        type: string
                        title: 刷新token
                      access_expires_at:
                        type: integer
                        title: token过期时间
                      refresh_expires_at:
                        type: integer
                        title: 刷新token过期时间
                    required:
                      - token
                      - refresh_token
                      - access_expires_at
                      - refresh_expires_at
                    x-apifox-orders:
                      - token
                      - refresh_token
                      - access_expires_at
                      - refresh_expires_at
                  code:
                    type: integer
                required:
                  - message
                  - data
                  - code
                x-apifox-orders:
                  - message
                  - data
                  - code
              example:
                message: 操作成功！
                data:
                  token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwic3ViIjoiY2M3MWRiNzMtOWE3OC00YTlhLTg1YzUtMDg1MDc1ZjI4N2EzIiwiZXhwIjoxNzU1NDkxODgxLCJuYmYiOjE3NTU0ODgyODEsImlhdCI6MTc1NTQ4ODI4MSwianRpIjoiYWQ0Y2U4ZTEtMTNlNC00OGMwLWIyMTAtNTQyYzI1N2Q1OGJlIn0.PNr-nCZHDUvU4f19TSWWuXlzqxKrX_znqrNlFaKDMPI
                  refresh_token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsInN1YiI6ImNjNzFkYjczLTlhNzgtNGE5YS04NWM1LTA4NTA3NWYyODdhMyIsImV4cCI6MTc1NjA5MzA4MSwibmJmIjoxNzU1NDg4MjgxLCJpYXQiOjE3NTU0ODgyODEsImp0aSI6ImFkNGNlOGUxLTEzZTQtNDhjMC1iMjEwLTU0MmMyNTdkNThiZSJ9.ekDnVFO8vYk3oP0mcl_l_WOnHYdRlZSTzs8hH5DWLsM
                  access_expires_at: 1755491881
                  refresh_expires_at: 1756093081
                code: 200000
          headers: {}
          x-apifox-name: 成功
      security:
        - bearer: []
      x-apifox-folder: 登入相关
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-347371357-run
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: ''
    description: 云端 Mock
security: []

```

# 获取商业化配置文件

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /v1/products:
    get:
      summary: 获取商业化配置文件
      deprecated: false
      description: ''
      tags:
        - 商业化
      parameters:
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      subscriptions:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              title: 订阅ID
                            product_id:
                              type: string
                              title: 订阅ID
                            group_id:
                              type: string
                              title: 组ID
                            type:
                              type: integer
                              title: 类型
                              enum:
                                - 1
                                - 2
                              x-apifox-enum:
                                - value: 1
                                  name: 订阅类型
                                  description: ''
                                - value: 2
                                  name: 消耗品
                                  description: ''
                            name:
                              type: string
                              title: 套餐名称
                            desc:
                              type: string
                              title: 套餐描述
                            price:
                              type: string
                              title: 价格
                            fake_price:
                              type: string
                              title: 假价格
                              description: 低至xx
                            discount:
                              type: integer
                              title: 折扣
                            discount_price:
                              type: string
                              title: 折扣价
                            level:
                              type: integer
                              title: 等级
                            points:
                              type: integer
                              title: 积分数
                          required:
                            - id
                            - product_id
                            - group_id
                            - type
                            - name
                            - desc
                            - price
                            - fake_price
                            - discount
                            - discount_price
                            - level
                            - points
                          x-apifox-orders:
                            - id
                            - product_id
                            - group_id
                            - type
                            - name
                            - desc
                            - price
                            - fake_price
                            - discount
                            - discount_price
                            - level
                            - points
                        title: 订阅
                    required:
                      - subscriptions
                    x-apifox-orders:
                      - subscriptions
                  code:
                    type: integer
                required:
                  - message
                  - data
                  - code
                x-apifox-orders:
                  - message
                  - data
                  - code
              example:
                message: 操作成功！
                data:
                  subscriptions:
                    - id: 1
                      product_id: mjc.vip.year
                      group_id: '1'
                      type: 1
                      name: 年度会员
                      desc: 年度会员
                      price: '498.00'
                      fake_price: '1.30'
                      discount: 0
                      discount_price: '0.00'
                      level: 4
                      points: 0
                    - id: 2
                      product_id: mjc.vip.quarter
                      group_id: '1'
                      type: 1
                      name: 季度会员
                      desc: 季度会员
                      price: '168.00'
                      fake_price: '1.80'
                      discount: 0
                      discount_price: '0.00'
                      level: 3
                      points: 0
                    - id: 3
                      product_id: mjc.vip.month
                      group_id: '1'
                      type: 1
                      name: 月费会员
                      desc: 月费会员
                      price: '78.00'
                      fake_price: '2.50'
                      discount: 0
                      discount_price: '0.00'
                      level: 2
                      points: 0
                    - id: 4
                      product_id: mjc.vip.week
                      group_id: '1'
                      type: 1
                      name: 周费会员
                      desc: 周费会员
                      price: '38.00'
                      fake_price: '5.40'
                      discount: 0
                      discount_price: '0.00'
                      level: 1
                      points: 0
                code: 200000
          headers: {}
          x-apifox-name: 成功
      security:
        - bearer: []
      x-apifox-folder: 商业化
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-342175205-run
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: http://interstellar.a22t.com
    description: 测试环境
security: []

```

# 订阅验证

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /v1/subscriptions/{id}:
    post:
      summary: 订阅验证
      deprecated: false
      description: ''
      tags:
        - 商业化
      parameters:
        - name: id
          in: path
          description: 订阅id
          required: true
          example: 1
          schema:
            type: integer
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction_id:
                  type: string
                  title: 原始订单ID
              x-apifox-orders:
                - transaction_id
            example:
              transaction_id: '11'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      is_check_passed:
                        type: boolean
                        title: 是否能购买
                      need_confirm:
                        type: boolean
                        title: 是否需要再次确认
                        description: 如果为 true 必须要弹窗确认
                      tips:
                        type: string
                        title: 提示消息
                    required:
                      - is_check_passed
                      - need_confirm
                      - tips
                    x-apifox-orders:
                      - is_check_passed
                      - need_confirm
                      - tips
                  code:
                    type: integer
                required:
                  - message
                  - data
                  - code
                x-apifox-orders:
                  - message
                  - data
                  - code
              example:
                message: 操作成功！
                data:
                  is_check_passed: true
                  need_confirm: false
                  tips: 检测到您要开始新的订阅，是否确认继续？
                code: 200000
          headers: {}
          x-apifox-name: 成功
      security:
        - bearer: []
      x-apifox-folder: 商业化
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-342175206-run
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: http://interstellar.a22t.com
    description: 测试环境
security: []

```

# 订阅交付

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /v1/subscriptions/deliver:
    post:
      summary: 订阅交付
      deprecated: false
      description: ''
      tags:
        - 商业化
      parameters:
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction_id:
                  type: string
                  title: 订单ID
              required:
                - transaction_id
              x-apifox-orders:
                - transaction_id
            example:
              transaction_id: '1'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      is_deliver:
                        type: boolean
                        title: 是否成功交付
                    required:
                      - is_deliver
                    x-apifox-orders:
                      - is_deliver
                  code:
                    type: integer
                required:
                  - message
                  - data
                  - code
                x-apifox-orders:
                  - message
                  - data
                  - code
              example:
                message: 操作成功！
                data:
                  is_deliver: false
                code: 200000
          headers: {}
          x-apifox-name: 成功
      security:
        - bearer: []
      x-apifox-folder: 商业化
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-342175208-run
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: ''
    description: 云端 Mock
security: []

```

# 获取用户状态

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /v1/user:
    get:
      summary: 获取用户状态
      deprecated: false
      description: ''
      tags:
        - 我的
      parameters:
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        title: ID
                      name:
                        type: string
                        title: 用户名
                      phone:
                        type: string
                        title: 手机号
                      free_points:
                        type: number
                        title: 免费积分
                        description: 浮点数
                      recharge_points:
                        type: number
                        title: 永久积分
                        description: 浮点数
                      subscription_points:
                        type: number
                        title: 订阅积分
                        description: 浮点数
                      status:
                        type: integer
                        title: 状态
                      uuid:
                        type: string
                        title: 用户唯一ID
                      vip:
                        type: integer
                        title: vip 等级
                        enum:
                          - 0
                          - 1
                          - 2
                          - 3
                          - 4
                        x-apifox-enum:
                          - value: 0
                            name: 无会员
                            description: ''
                          - value: 1
                            name: 周会员
                            description: ''
                          - value: 2
                            name: 月会员
                            description: ''
                          - value: 3
                            name: 季会员
                            description: ''
                          - value: 4
                            name: 年会员
                            description: ''
                      vip_expired_time:
                        type: integer
                        title: vip 过期时间
                    required:
                      - id
                      - name
                      - phone
                      - free_points
                      - recharge_points
                      - subscription_points
                      - status
                      - uuid
                      - vip
                      - vip_expired_time
                    x-apifox-orders:
                      - id
                      - name
                      - phone
                      - free_points
                      - recharge_points
                      - subscription_points
                      - status
                      - uuid
                      - vip
                      - vip_expired_time
                  code:
                    type: integer
                required:
                  - message
                  - data
                  - code
                x-apifox-orders:
                  - message
                  - data
                  - code
              example:
                message: 操作成功！
                data:
                  id: 14
                  name: C3hkN7by
                  phone: '15111222771'
                  free_points: 0
                  recharge_points: 140
                  subscription_points: 0
                  status: 0
                  uuid: cc71db73-9a78-4a9a-85c5-085075f287a3
                  vip: 0
                  vip_expired_time: 0
                code: 200000
          headers: {}
          x-apifox-name: 成功
      security:
        - bearer: []
      x-apifox-folder: 我的
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-342175209-run
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: ''
    description: 云端 Mock
security: []

```

# 我的作品

## OpenAPI Specification

```yaml
openapi: 3.0.1
info:
  title: ''
  version: 1.0.0
paths:
  /user/works:
    get:
      summary: 我的作品
      deprecated: false
      description: ''
      tags:
        - 我的
      parameters:
        - name: CLIENT-UDID
          in: header
          description: 设备唯一标识符
          example: '{{udid}}'
          schema:
            type: string
            default: '{{udid}}'
        - name: CLIENT-PLATFORM
          in: header
          description: 设备当前平台
          example: '{{platform}}'
          schema:
            type: string
            default: '{{platform}}'
        - name: CLIENT-VERSION
          in: header
          description: 设备当前APP版本
          example: '{{version}}'
          schema:
            type: string
            default: '{{version}}'
        - name: ACCEPT-LANGUAGE
          in: header
          description: 语言
          example: zh-CN
          schema:
            type: string
            default: zh-CN
            enum:
              - zh-CH
              - pt
            x-apifox-enum:
              - value: zh-CH
                name: 中文
                description: ''
              - value: pt
                name: 葡萄牙语
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          title: 任务id
                        status:
                          type: integer
                          title: 状态
                          enum:
                            - 0
                            - 1
                            - 2
                            - -1
                            - -2
                          x-apifox-enum:
                            - value: 0
                              name: 任务开始
                              description: ''
                            - value: 1
                              name: 任务进行
                              description: ''
                            - value: 2
                              name: 任务成功
                              description: ''
                            - value: -1
                              name: 任务失败
                              description: ''
                            - value: -2
                              name: 任务超时
                              description: ''
                        type:
                          type: integer
                          title: 模型类型
                          enum:
                            - 1
                            - 2
                          x-apifox-enum:
                            - value: 1
                              name: luma
                              description: ''
                            - value: 2
                              name: mj
                              description: ''
                          x-apifox-mock: '1'
                        content:
                          type: object
                          properties:
                            prompt:
                              type: string
                              title: 提示词
                              x-apifox-mock: '{{$lorem.sentence}}'
                          required:
                            - prompt
                          x-apifox-orders:
                            - prompt
                          title: 请求内容
                          description: 请查看请求接口
                        images:
                          type: array
                          items:
                            type: string
                            x-apifox-mock: >-
                              https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                          title: 图片结果
                          maxItems: 4
                          minItems: 4
                        created_at:
                          type: string
                          title: 创建时间
                          x-apifox-mock: '{{$date.anytime|format(''yyyy-MM-dd HH:mm:ss'')}}'
                        updated_at:
                          type: string
                          title: 更新时间
                          x-apifox-mock: '{{$date.anytime|format(''yyyy-MM-dd HH:mm:ss'')}}'
                      required:
                        - id
                        - status
                        - type
                        - images
                        - content
                        - created_at
                        - updated_at
                      x-apifox-orders:
                        - id
                        - status
                        - type
                        - images
                        - content
                        - created_at
                        - updated_at
                  message:
                    type: string
                  pager:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        title: 当前页
                      per_page:
                        type: integer
                        title: 每页条数
                      total_page:
                        type: integer
                        title: 总页数
                      total_count:
                        type: integer
                        title: 总条数
                      next_page_url:
                        type: string
                        title: 下一页的链接
                      prev_page_url:
                        type: string
                        title: 上一页的链接
                    required:
                      - current_page
                      - per_page
                      - total_page
                      - total_count
                      - next_page_url
                      - prev_page_url
                    x-apifox-orders:
                      - current_page
                      - per_page
                      - total_page
                      - total_count
                      - next_page_url
                      - prev_page_url
                required:
                  - code
                  - data
                  - message
                  - pager
                x-apifox-orders:
                  - code
                  - data
                  - message
                  - pager
              example:
                code: 45
                data:
                  - id: 40
                    status: 2
                    type: 1
                    images:
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                    content:
                      prompt: 计段发议十表利年情进。
                    created_at: '2025-06-21 19:48:57'
                    updated_at: '2024-12-27 17:52:35'
                  - id: 74
                    status: 2
                    type: 1
                    images:
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                    content:
                      prompt: 价断即完组总比。
                    created_at: '2025-04-18 13:45:23'
                    updated_at: '2025-07-15 17:26:17'
                  - id: 83
                    status: 2
                    type: 1
                    images:
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                      - >-
                        https://testbucket0x.oss-cn-beijing.aliyuncs.com/gfast/dcmkryvlbhiyyybaec.png
                    content:
                      prompt: 西称格支育素持除总。
                    created_at: '2026-06-24 03:25:43'
                    updated_at: '2026-01-15 22:38:28'
                message: est incididunt dolor non ea
                pager:
                  current_page: 8
                  per_page: 60
                  total_page: 89
                  total_count: 42
                  next_page_url: https://mushy-colon.biz/
                  prev_page_url: https://warped-trash.info/
          headers: {}
          x-apifox-name: 成功
      security: []
      x-apifox-folder: 我的
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/7020404/apis/api-359615782-run
components:
  schemas: {}
  securitySchemes: {}
servers:
  - url: http://interstellar.a22t.com
    description: 测试环境
security: []

```